### ISSUE TITLE
TypeError: Path must be a string. Received { app: './client/app.js', vendor: [ 'echarts' ] }

### ISSUE THREAD

**Issue by sheguloves** [webpack/karma-webpack#169]
I'm submitting a bug report:

when I use karma-webpack with webpack configuration, I got this error:

```
23 08 2016 10:36:40.055:ERROR [config]: Invalid config file!
  TypeError: Path must be a string. Received { app: './client/app.js', ven
dor: [ 'echarts' ] }
    at assertPath (path.js:8:11)
    at Object.win32.resolve (path.js:130:5)
    at Object.<anonymous> (D:\cubedesigner\karma.conf.js:37:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.parseConfig (D:\cubedesigner\node_modules\karma\lib\config.js:307:
22)
    at new Server (D:\cubedesigner\node_modules\karma\lib\server.js:56:20)
    at Object.exports.run (D:\cubedesigner\node_modules\karma\lib\cli.js:266:7)
    at Object.<anonymous> (D:\cubedesigner\node_modules\karma\bin\karma:3:23)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)

```

This is my webpack.conf.js

```
module.exports = function() {
    return {
        entry:  {
            app: './client/app.js',
            vendor: ['echarts']
        }
        debug: true
    };
};
```

even I add resolve.alias, it still doesn't work

```
module.exports = function() {
    return {
        entry:  {
            app: './client/app.js',
            vendor: ['echarts']
        }
        debug: true,
        resolve: {
            alias: {
                'echarts': "node_modules/echarts"
            },
            extensions: ['', '.js', '.jsx']
        }
    };
};
```

but webpack.conf.js is work well for dev

**Webpack version**: 1.13.1
**Webpack Karma version**: 1.8.0
**Karma version**: 1.2.0
**Windows 7**
**Browser**: Chrome Version 52.0.2743.116 (64-bit)

**Comment by sheguloves** [comment]
Sorry, it is my fault, I use object in config.set({file: []}).
