### ISSUE TITLE
Can not load "webpack"

### ISSUE THREAD

**Issue by egoroof** [webpack/karma-webpack#192]
**I'm submitting a bug report**

**Webpack version:**
2.2.0-rc.4

**Webpack Karma version**:
1.8.1

**Karma version**:
1.3.0

**Please tell us about your environment:**
Windows 10

**Browser:** [Chrome 55 | Firefox 50.1.0 | IE 11 | Edge 14]

**Current behavior:**

Running karma results in:

```
12 01 2017 00:39:45.143:ERROR [preprocess]: Can not load "webpack"!
  Error
    at webpack (E:\Dropbox\repo\browser-id3-writer\node_modules\webpack\lib\webpack.js:19:9)
    at new Plugin (E:\Dropbox\repo\browser-id3-writer\node_modules\karma-webpack\lib\karma-webpack.js:63:18)
    at invoke (E:\Dropbox\repo\browser-id3-writer\node_modules\di\lib\injector.js:75:15)
    at Array.instantiate (E:\Dropbox\repo\browser-id3-writer\node_modules\di\lib\injector.js:59:20)
    at get (E:\Dropbox\repo\browser-id3-writer\node_modules\di\lib\injector.js:48:43)
    at E:\Dropbox\repo\browser-id3-writer\node_modules\di\lib\injector.js:71:14
    at Array.map (native)
    at Array.invoke (E:\Dropbox\repo\browser-id3-writer\node_modules\di\lib\injector.js:70:31)
    at Injector.get (E:\Dropbox\repo\browser-id3-writer\node_modules\di\lib\injector.js:48:43)
    at instantiatePreprocessor (E:\Dropbox\repo\browser-id3-writer\node_modules\karma\lib\preprocessor.js:55:20)
    at Array.forEach (native)
    at createPreprocessor (E:\Dropbox\repo\browser-id3-writer\node_modules\karma\lib\preprocessor.js:74:20)
    at Array.invoke (E:\Dropbox\repo\browser-id3-writer\node_modules\di\lib\injector.js:75:15)
    at get (E:\Dropbox\repo\browser-id3-writer\node_modules\di\lib\injector.js:48:43)
    at E:\Dropbox\repo\browser-id3-writer\node_modules\di\lib\injector.js:71:14
    at Array.map (native)
12 01 2017 00:39:45.295:INFO [karma]: Karma v1.3.0 server started at http://localhost:9876/
12 01 2017 00:39:45.296:INFO [launcher]: Launching browsers Chrome, Firefox, IE, Edge with unlimited concurrency
12 01 2017 00:39:45.297:ERROR [karma]: Found 1 load error

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test:browser"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! browser-id3-writer@3.0.2 test:browser: `karma start tools/karma.conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the browser-id3-writer@3.0.2 test:browser script 'karma start tools/karma.conf.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the browser-id3-writer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     karma start tools/karma.conf.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs browser-id3-writer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls browser-id3-writer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Dropbox\repo\browser-id3-writer\npm-debug.log
```

**Expected/desired behavior:**

It should work 😄 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**

Just updated webpack from 2.2.0-rc.3 to 2.2.0-rc.4 and this is happened. All source code is here: https://github.com/egoroof/browser-id3-writer

**What is the expected behavior?**

It should work 😄, but I already answered for it before, edit the template!

**What is the motivation / use case for changing the behavior?**

To get users happy.

p.s. webpack made a lot of refactoring in rc and also introduced breaking change, that's not sweet...

**Comment by d3viant0ne** [comment]
@egoroof - Update to [Karma-Webpakc 2.0.0](https://github.com/webpack/karma-webpack/releases/tag/v2.0.0)

Be sure to read the note on the breaking change :)

**Comment by egoroof** [comment]
It's fixed now, thanks!

**Comment by brutalcrozt** [comment]
@d3viant0ne Thanks for the lib Joshua, 

I still got this error with my environment :
>Webpack version:
3.6.0
karma-webpack version:
2.0.5
Karma version:
1.7.1
Please tell us about your environment:
Windows 8
Browser: [Chrome 55]

Which actually just because i miss **registering karma-webpack as plugins** on the karma configuration.
But according the readme, it's still miss the plugins section, If you desire, i will make a PR for that
