### ISSUE TITLE
Using ES5 getter syntax for output.filename make test fail with weird output

### ISSUE THREAD

**Issue by sairion** [webpack/karma-webpack#38]
```
DEBUG [plugin]: Loading plugin karma-spec-reporter.
DEBUG [plugin]: Loading plugin karma-mocha.
DEBUG [plugin]: Loading plugin karma-chrome-launcher.
DEBUG [plugin]: Loading plugin karma-webpack.
INFO [karma]: Karma v0.12.31 server started at http://localhost:9876/
INFO [launcher]: Starting browser Chrome
DEBUG [temp-dir]: Creating temp dir at /tmp/karma-16389635
DEBUG [launcher]: google-chrome --user-data-dir=/tmp/karma-16389635 --no-default-browser-check --no-first-run --disable-default-apps --disable-popup-blocking --disable-translate http://localhost:9876
/?id=16389635
DEBUG [web-server]: serving: /home/jaylee/dodo/dodo/node_modules/karma/static/client.html
DEBUG [web-server]: serving: /home/jaylee/dodo/dodo/node_modules/karma/static/karma.js
DEBUG [web-server]: upgrade /socket.io/1/websocket/Q06cJkWUBhAqkFhw9iaA
DEBUG [karma]: A browser has connected on socket Q06cJkWUBhAqkFhw9iaA
INFO [Chrome 39.0.2171 (Linux)]: Connected on socket Q06cJkWUBhAqkFhw9iaA with id 16389635
DEBUG [launcher]: Chrome (id 16389635) captured in 5.678 secs
DEBUG [karma]: All browsers are ready, executing
ERROR [karma]: [Error: Path doesn't exist '/_karma_webpack_/spec/api-base.spec.js']
Error: Path doesn't exist '/_karma_webpack_/spec/api-base.spec.js'
  at MemoryFileSystem.readFileSync (/home/jaylee/dodo/dodo/node_modules/karma-webpack/node_modules/webpack-dev-middleware/node_modules/memory-fs/lib/MemoryFileSystem.js:75:10)
  at MemoryFileSystem.readFile (/home/jaylee/dodo/dodo/node_modules/karma-webpack/node_modules/webpack-dev-middleware/node_modules/memory-fs/lib/MemoryFileSystem.js:201:21)
  at doRead (/home/jaylee/dodo/dodo/node_modules/karma-webpack/index.js:157:26)
  at Plugin.readFile (/home/jaylee/dodo/dodo/node_modules/karma-webpack/index.js:161:3)
  at process._tickCallback (node.js:419:13)

DEBUG [launcher]: Disconnecting all browsers
Hash: e18a7201bbbb0855359a
Version: webpack 1.4.14
```

`webpack.config.js` was like this:

```js
module.exports = {
    devtool: 'eval',
    contentBase: STATIC_PATH,
    entry: [
        STATIC_PATH
    ],
    output: {
        path: STATIC_BUILT_PATH,
        get filename () {
            if (Prod)
                return 'bundle-' + (process.env.DEPLOY_ID || Math.floor(Math.random() * 1000000)) + '.js';
            else
                return 'bundle.js';
        },
    },

};
```
after changing getter syntax to string, there is no problem.

**Comment by barsukov** [comment]
I still have this problem with karma

**Comment by sokra** [comment]
You should not use `output` with karma-webpack, as karma-webpack doesn't output anything.

**Comment by sairion** [comment]
Ah, ok. Since I'm not bothered by this anymore, I'm closing this.
