### ISSUE TITLE
Error: No template for dependency: TemplateArgumentDependency

### ISSUE THREAD

**Issue by nishp1** [webpack/karma-webpack#41]
I am currently using webpack version 1.5.0 and karma-webpack version 1.5.3 on a project. After release of webpack version 1.6.0, I am getting the error below when running tests. 

It looks like having webpack ^1.4.0 as a peerDependencies causes npm to download the latest webpack under karma-webpack's node_modules even though webpack 1.5.3 satisfies peerDependencies requirement. Any thoughts on how to avoid these issues going further?

```
Error: No template for dependency: TemplateArgumentDependency
  at doDep (project/node_modules/karma-webpack/node_modules/webpack/lib/NormalModule.js:115:23)
  at Array.forEach (native)
  at doBlock (project/node_modules/karma-webpack/node_modules/webpack/lib/NormalModule.js:124:22)
  at DependenciesBlock.NormalModule.source (project/node_modules/karma-webpack/node_modules/webpack/lib/NormalModule.js:156:2)
  at Tapable.ModuleTemplate.render (project/node_modules/karma-webpack/node_modules/webpack/lib/ModuleTemplate.js:14:28)
  at Tapable.Template.renderChunkModules (project/node_modules/karma-webpack/node_modules/webpack/lib/Template.js:80:31)
  at Tapable.<anonymous> (project/node_modules/karma-webpack/node_modules/webpack/lib/MainTemplate.js:28:22)
  at Tapable.applyPlugins [as applyPluginsWaterfall] (project/node_modules/karma-webpack/node_modules/webpack/node_modules/tapable/lib/Tapable.js:37:47)
  at Tapable.MainTemplate.render (project/node_modules/karma-webpack/node_modules/webpack/lib/MainTemplate.js:112:20)
  at Tapable.createChunkAssets (project/node_modules/karma-webpack/node_modules/webpack/lib/Compilation.js:783:32)
```

**Comment by nishp1** [comment]
Any thoughts?

Now getting following error with the upgrade of webpack to 1.7.0.
```
WARN [preprocess]: Can not load "webpack"!
  TypeError: Cannot read property 'filename' of null
```

**Comment by songawee** [comment]
This seems to be our issue as well. @nishp1 Have you found a good workaround yet? cc @sokra

**Comment by nishp1** [comment]
I ended up upgrading webpack to latest version so that there is only version of webpack.

**Comment by idchlife** [comment]
Just now encountered error 

    /Users/myuser/www/react-test/scripts/node_modules/webpack/lib/Template.js:80
                                source.add(BalancePanel.render(module, dependencyTemplates, chunk));
                                           ^
    ReferenceError: BalancePanel is not defined


When BalancePanel was my file and my class, not webpacks

I commented this

    //var webpack = require('webpack');

and this

    //new webpack.DefinePlugin({
    //  'process.env': {
    //    'NODE_ENV': JSON.stringify('production')
    //  }
    //})

in webpack.config.js file, also deleted **webpack** folder from node_modules, so exactly webpack from /usr/local/bin/webpack will be used.

Yep, I assume when using production plugin I will need to use it once and not in dev, otherwise I will end up with webpack trying to insert my classes in its source code (or I'm stupid)

**Comment by idchlife** [comment]
Addition. I also had to delete react and react-tools folders, after minification/stringification (or what it is), so they won't search for my class.

**Comment by eugene1g** [comment]
I had the same issue while using a global install of webpack and webpack-dev-server (current). With no  other changes, it just started throwing that error one morning. I removed webpack and webpack-dev-server from global node_modules, installed both again and they worked fine again. Probably something going wrong with dependencies.

**Comment by gajus** [comment]
Are you using `webpack.optimize.DedupePlugin()` plugin? Removing the latter plugin from my config solved the issue.

**Comment by gajus** [comment]
In addition, see https://github.com/webpack/webpack/issues/1082.

**Comment by d3viant0ne** [comment]
Resolving as this is no longer valid in `2.2.0` and resolved for `1.x`
