### ISSUE TITLE
Problems with regular expressions in karma.webpack configuration

### ISSUE THREAD

**Issue by mendlik** [webpack/karma-webpack#42]
I have a problem with karma-webpack configuration. It occurs when I use regular expressions in `webpack.module.loaders[].test` field.

**Error message**

```
[13:53:20] Starting Karma server...
INFO [karma]: Karma v0.12.31 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
ERROR [karma]: [Error: [object Object] is not a valid test]
Error: [object Object] is not a valid test
    at asMatcher (C:\Users\xxx\Development\yyy\node_modules\webpack\node_modules\webpack-core\lib\LoadersList.js:48:9)
    at LoadersList.matchPart (C:\Users\xxx\Development\yyy\node_modules\webpack\node_modules\webpack-core\lib\LoadersList.js:65:16)
    at LoadersList.matchObject (C:\Users\xxx\Development\yyy\node_modules\webpack\node_modules\webpack-core\lib\LoadersList.js:90:12)
    at LoadersList.<anonymous> (C:\Users\xxx\Development\yyy\node_modules\webpack\node_modules\webpack-core\lib\LoadersList.js:77:12)
    at Array.map (native)
    at LoadersList.match (C:\Users\xxx\Development\yyy\node_modules\webpack\node_modules\webpack-core\lib\LoadersList.js:70:19)
    at Tapable.<anonymous> (C:\Users\xxx\Development\yyy\node_modules\webpack\lib\NormalModuleFactory.js:81:64)
    at C:\Users\xxx\Development\yyy\node_modules\async\lib\async.js:254:17
    at done (C:\Users\xxx\Development\yyy\node_modules\async\lib\async.js:135:19)
    at C:\Users\xxx\Development\yyy\node_modules\async\lib\async.js:32:16
```

**Additional log**
When I do `consoloe.log('>>>', test)` in line `webpack-core\lib\LoadersList.js:48` output shows: `>>> {}`.

**Karma configuration**

```js
{
  /* ... some non important settings */

  /* ... webpack settings */
  webpack: {
    module: {
      loaders: [
        /* problematic regexes in test fields */
        { test: /\.html$/, loader: 'swig-loader?varControls[]={:&varControls[]=:}' },
        { test: /\.json$/, loader: 'json-loader' }
      ]
    }
  }
}
```
I am using:
- karma-webpack v1.5.0
- webpack v1.7.2
- karma v0.12.31
- gulp-karma v0.0.4

**Comment by mendlik** [comment]
Sorry, now I can see the problem.
It's in gulp-karma line 72.

They do `JSON.stringify(options)` and than all regexes are converted to `{}`.

Did anyone find a clean solution for this problem?

**Comment by mendlik** [comment]
Resolved here: https://github.com/lazd/gulp-karma/issues/37#issuecomment-77195552
