### ISSUE TITLE
Can't find framework:webpack

### ISSUE THREAD

**Issue by yoni-tock** [webpack/karma-webpack#46]
I've tried a bunch of different tweaks to my karma config file and nothing seems to work.
Here's the error: `Error: No provider for "framework:webpack"! (Resolving: framework:webpack)`

Any help is appreciated!

```js
module.exports = function(config) {
  config.set({
    basePath: __dirname,
    plugins: [
      require("karma-webpack")
    ],
    frameworks: ['jasmine', 'sinon'],

    files: [
      'dist/styles/main.css',
      'test/**/*.js'
    ],

    preprocessors: {
      'test/**/*.js': ['webpack'],
    },

    webpack: require('./webpack.config.js'),

    reporters: ['spec'],

    port: 9876,

    colors: true,

    logLevel: config.LOG_INFO,

    autoWatch: false,

    browsers: ['Chrome'],

    browserNoActivityTimeout: 60000,

    singleRun: true
  });
};

```

**Comment by SimenB** [comment]
remove the `plugins`-field, `karma` automatically includes all `karma-` packages.

I got the same error you did when having `'webpack'` in frameworks, make sure that's not the case.

**Comment by haimich** [comment]
I had the same problem, only the error message would be:

```
/home/juicebox/Code/karma-test/node_modules/karma/node_modules/di/lib/injector.js:9
      throw error('No provider for "' + name + '"!');
            ^
Error: No provider for "framework:jasmine"! (Resolving: framework:jasmine)
    at error (/home/juicebox/Code/karma-test/node_modules/karma/node_modules/di/lib/injector.js:22:68)
    at Object.parent.get (/home/juicebox/Code/karma-test/node_modules/karma/node_modules/di/lib/injector.js:9:13)
    at get (/home/juicebox/Code/karma-test/node_modules/karma/node_modules/di/lib/injector.js:54:19)
    at /home/juicebox/Code/karma-test/node_modules/karma/lib/server.js:29:14
    at Array.forEach (native)
    at start (/home/juicebox/Code/karma-test/node_modules/karma/lib/server.js:28:21)
    at invoke (/home/juicebox/Code/karma-test/node_modules/karma/node_modules/di/lib/injector.js:75:15)
    at Object.exports.start (/home/juicebox/Code/karma-test/node_modules/karma/lib/server.js:307:12)
    at Object.exports.run (/home/juicebox/Code/karma-test/node_modules/karma/lib/cli.js:220:27)
    at Object.<anonymous> (/home/juicebox/Code/karma-test/node_modules/karma/bin/karma:3:23)
```

After removing the plugin section as described by @SimenB it worked!

**Comment by volkanunsal** [comment]
Having the same problem. Removing the plugins section didn't work for me.

**Comment by volkanunsal** [comment]
It turned out that I had put webpack in `frameworks` field. Removing it from there eliminated the error.

**Comment by mingzepeng** [comment]
@haimich  i met the same problem, thanks for your solution

**Comment by leeching** [comment]
@SimenB It is the right way. Thanks! `Readme.md` should be updated.
