### ISSUE TITLE
Karma 0.13.0 - "Can not resolve circular dependency!"

### ISSUE THREAD

**Issue by nhunzaker** [webpack/karma-webpack#62]
After upgrading to Karma 0.13.0, I'm hitting the following issue:

```
16 07 2015 08:23:32.494:WARN [preprocess]: Can not load "webpack"!
  Error: Can not resolve circular dependency! (Resolving: preprocessor:webpack -> webpackPlugin -> preprocessor:webpack)
    at error (project/node_modules/karma/node_modules/di/lib/injector.js:22:68)
    at get (project/node_modules/karma/node_modules/di/lib/injector.js:44:15)
    at instantiatePreprocessor (project/node_modules/karma/lib/preprocessor.js:56:37)
    at Array.forEach (native)
    at null.<anonymous> (project/node_modules/karma/lib/preprocessor.js:77:31)
    at tryCatcher (project/node_modules/karma/node_modules/bluebird/js/main/util.js:26:23)
    at ret [as _preprocess] (eval at <anonymous> (project/node_modules/karma/node_modules/bluebird/js/main/promisify.js:163:12), <anonymous>:13:39)
    at project/node_modules/karma/lib/file-list.js:182:19
    at Array.map (native)
    atproject/node_modules/karma/lib/file-list.js:167:30
    at Array.map (native)
    at List._refresh (/project/node_modules/karma/lib/file-list.js:150:37)
    at List.refresh (/project/node_modules/karma/lib/file-list.js:249:27)
    at Plugin.notifyKarmaAboutChanges (/project/karma-webpack/index.js:109:16)
    at Plugin.<anonymous> (/project/node_modules/karma-webpack/index.js:73:9)
    at Tapable.applyPlugins (/project/node_modules/webpack/node_modules/tapable/lib/Tapable.js:26:37)
```

I'll keep investigating on my own, but I thought I'd report it in any case.

**Comment by nhunzaker** [comment]
It looks like similar reports are coming through on Karma's end:

https://github.com/karma-runner/karma/issues/1497

**Comment by Uter1007** [comment]
Have the same error....

**Comment by danpantry** [comment]
+1

**Comment by archangel-irk** [comment]
+1

**Comment by marr** [comment]
bump

**Comment by greypants** [comment]
+1

Oh hey @nhunzaker

**Comment by gabel** [comment]
:+1:

**Comment by maikdiepenbroek** [comment]
Cool thanks, after downgrading to 0.12.37 it also works.

**Comment by tupy** [comment]
+1

**Comment by vectart** [comment]
+1!!!!1111

**Comment by jingzhou123** [comment]
+1

**Comment by mllocs** [comment]
+1

**Comment by n1k0** [comment]
+1000^42

**Comment by ebaranov** [comment]
+1

**Comment by richard-lopes** [comment]
I second.

**Comment by davidagraf** [comment]
+1

**Comment by vectart** [comment]
Let's merge PR #64 :-)

**Comment by vectart** [comment]
Or #63 though

**Comment by andrefarzat** [comment]
+1

**Comment by danpantry** [comment]
hooray :smile:
