### ISSUE TITLE
Can not load "webpack"

### ISSUE THREAD

**Issue by adrianleb** [webpack/karma-webpack#68]
1.7.0 karma-webpack started breaking karma tests, 1.6.0 works as expected.
running on:

node v0.10.33
npm v2.12.0
karma v0.12.37
webpack v1.10.5
```
WARN [preprocess]: Can not load "webpack"!
  TypeError: Object [object Object] has no method 'refreshFiles'
    at Plugin.notifyKarmaAboutChanges (node_modules/karma-webpack/index.js:108:15)
    at Plugin.<anonymous> (node_modules/karma-webpack/index.js:72:9)
    at Tapable.applyPlugins (node_modules/webpack/node_modules/tapable/lib/Tapable.js:26:37)
    at Watching._done (node_modules/webpack/lib/Compiler.js:78:17)
    at Watching.<anonymous> (node_modules/webpack/lib/Compiler.js:61:18)
    at Tapable.emitRecords (node_modules/webpack/lib/Compiler.js:281:37)
    at Watching.<anonymous> (node_modules/webpack/lib/Compiler.js:58:19)
    at /home/ubuntu/gropius/resources/front-ends/application/node_modules/webpack/lib/Compiler.js:274:11
    at Tapable.applyPluginsAsync (node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Tapable.afterEmit (node_modules/webpack/lib/Compiler.js:271:8)
```

**Comment by Dignifiedquire** [comment]
You need to upgrade karma to 0.13

**Comment by gil** [comment]
Duplicate of #65

**Comment by adrianleb** [comment]
Ok, I had karma locked at 0.12.x due to a previous problem with karma-webpack which was solved in this new version.

agree with @gil about broken semantic versioning, one might have other reasons to have karma at a locked at a lower version and any given package.json with karma-webpack at `^1.6.0` (notice the tilde) will give devs a headache with this version.

closing this since my problem was solved by updating karma.
