### ISSUE TITLE
karma-webpack 1.7.0 causes error Can not load "webpack"!  TypeError: undefined is not a function

### ISSUE THREAD

**Issue by dgwaldo** [webpack/karma-webpack#74]
Here is my Karma config

    var Path = require('path');
    var _ = require('underscore');
    var args = BUILD_ARGS;

    var filePatterns = [
      Path.join(process.cwd(), 'node_modules/angular/angular.js'),
      Path.join(process.cwd(), 'node_modules/angular-mocks/angular-mocks.js'),
      Path.join(process.cwd(), 'test/spec/setup.coffee'),
      Path.join(process.cwd(), 'test/spec/**/*.spec.coffee')
     ]

    var filePreprocessors = _(filePatterns).reduce(function (memo, val) {
      var prep = ['webpack'];
      memo[val] = prep;
      return memo;
     }, {});

    module.exports = function(config) {
       config.set({

        singleRun: true,

         frameworks: [
           'mocha', 
          'chai', 
          'chai-as-promised',
         'sinon-chai'
        ],
    
        browsers: ['PhantomJS'],

        files: filePatterns,
    
       preprocessors: filePreprocessors,
    
       webpack: require('../webpack/test'),

       reporters: args.reporter.split(','),

        coverageReporter: {
          dir: '../../../test/reports/coverage',
          reporters: [
            // reporters not supporting the `file` property 
           { type: 'html', subdir: 'report-html' },
           { type: 'lcov', subdir: 'report-lcov' },
           // reporters supporting the `file` property, use `subdir` to directly 
           // output them in the `dir` directory 
           { type: 'cobertura', subdir: '.', file: 'cobertura.txt' },
           { type: 'lcovonly', subdir: '.', file: 'report-lcovonly.txt' },
           { type: 'teamcity', subdir: '.', file: 'teamcity.txt' },
           { type: 'text', subdir: '.', file: 'text.txt' },
           { type: 'text-summary', subdir: '.', file: 'text-summary.txt' },
         ]
       },
    
       webpackMiddleware: { noInfo: true },

       colors: (args.color === false || args.colors === false) ? false : true,
    
       plugins: [
         'karma-webpack',
         'karma-chai-plugins',
         'karma-mocha',
         'karma-phantomjs-launcher',
         'karma-chrome-launcher',
         'karma-spec-reporter',
         'karma-nyan-reporter',
         'karma-notify-reporter',
         'karma-coverage',
        ]
      });
    }

     WARN [preprocess]: Can not load "webpack"!
     TypeError: undefined is not a function
      at Plugin.notifyKarmaAboutChanges (C:\Users\dwaldo\Documents\endeavor-      storefront\WebClient\node_modules\karma-webpack\index.js:108:15)
      at Plugin.<anonymous> (C:\Users\dwaldo\Documents\endeavor-    storefront\WebClient\node_modules\karma-webpack\index.js:72:9)
      at Tapable.applyPlugins (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\webpack\node_modules\tapable\lib\Tapable.js:26:37)
     at Watching._done (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\webpack\lib\Compiler.js:78:17)
     at Watching.<anonymous> (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\webpack\lib\Compiler.js:61:18)
     at Tapable.emitRecords (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\webpack\lib\Compiler.js:281:37)
     at Watching.<anonymous> (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\webpack\lib\Compiler.js:58:19)
     at C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\webpack\lib\Compiler.js:274:11
     at Tapable.applyPluginsAsync (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\webpack\node_modules\tapable\lib\Tapable.js:60:69)
      at Tapable.afterEmit (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\webpack\lib\Compiler.js:271:8)
      at Tapable.<anonymous> (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\webpack\lib\Compiler.js:266:14)
      at C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\webpack\node_modules\async\lib\async.js:52:16
      at Object.async.forEachOf.async.eachOf (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\webpack\node_modules\async\lib\async.js:231:20)
      at Object.async.forEach.async.each (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\webpack\node_modules\async\lib\async.js:210:22)
      at Tapable.emitFiles (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\webpack\lib\Compiler.js:234:20)
      at MemoryFileSystem.(anonymous function) [as mkdirp] (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\karma-webpack\node_modules\webpack-dev-middleware\node_
modules\memory-fs\lib\MemoryFileSystem.js:197:10)
      at Tapable.<anonymous> (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\webpack\lib\Compiler.js:228:25)
      at Tapable.applyPluginsAsync (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\webpack\node_modules\tapable\lib\Tapable.js:60:69)
      at Tapable.Compiler.emitAssets (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\webpack\lib\Compiler.js:225:7)
       at Watching.<anonymous> (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\webpack\lib\Compiler.js:54:18)
      at C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\webpack\lib\Compiler.js:402:12
      at Tapable.next (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\webpack\node_modules\tapable\lib\Tapable.js:67:11)
      at Tapable.<anonymous> (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\webpack\lib\CachePlugin.js:40:4)
      at Tapable.applyPluginsAsync (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\webpack\node_modules\tapable\lib\Tapable.js:71:13)
      at Tapable.<anonymous> (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\webpack\lib\Compiler.js:399:9)
      at Tapable.<anonymous> (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\webpack\lib\Compilation.js:574:13)
      at Tapable.applyPluginsAsync (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\webpack\node_modules\tapable\lib\Tapable.js:60:69)
      at Tapable.<anonymous> (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\webpack\lib\Compilation.js:569:10)
      at Tapable.applyPluginsAsync (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\webpack\node_modules\tapable\lib\Tapable.js:60:69)
      at Tapable.<anonymous> (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\webpack\lib\Compilation.js:564:9)
      at Tapable.applyPluginsAsync (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\webpack\node_modules\tapable\lib\Tapable.js:60:69)
      at Tapable.<anonymous> (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\webpack\lib\Compilation.js:560:8)
      at Tapable.applyPluginsAsync (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\webpack\node_modules\tapable\lib\Tapable.js:60:69)
     at Tapable.seal (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\webpack\lib\Compilation.js:522:7)
      at Tapable.<anonymous> (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\webpack\lib\Compiler.js:396:15)
       at C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\webpack\node_modules\tapable\lib\Tapable.js:103:11
       at Object.async.each (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\karma-webpack\node_modules\async\lib\async.js:118:20)
       at Plugin.make (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\karma-webpack\index.js:118:8)
      at Tapable.applyPluginsParallel (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\webpack\node_modules\tapable\lib\Tapable.js:107:14)
       at Tapable.Compiler.compile (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\webpack\lib\Compiler.js:393:7)
      at Watching.<anonymous> (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\webpack\lib\Compiler.js:46:17)
       at Tapable.next (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\webpack\node_modules\tapable\lib\Tapable.js:67:11)
       at Tapable.invalidAsyncPlugin (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\karma-webpack\node_modules\webpack-dev-middleware\middleware.js:78:3)
       at Tapable.applyPluginsAsync (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\webpack\node_modules\tapable\lib\Tapable.js:71:13)
      at Watching._go (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\webpack\lib\Compiler.js:44:16)
       at Watching.<anonymous> (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\webpack\lib\Compiler.js:36:8)
       at Tapable.readRecords (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\webpack\lib\Compiler.js:301:10)
      at new Watching (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\webpack\lib\Compiler.js:33:16)
     at Tapable.Compiler.watch (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\webpack\lib\Compiler.js:160:17)
     at new module.exports (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\karma-webpack\node_modules\webpack-dev-middleware\middleware.js:103:27)
      at new Plugin (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\karma-webpack\index.js:88:37)
       at invoke (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\karma\node_modules\di\lib\injector.js:75:15)
      at Array.instantiate (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\karma\node_modules\di\lib\injector.js:59:20)
      at get (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\karma\node_modules\di\lib\injector.js:48:43)
       at C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\karma\node_modules\di\lib\injector.js:71:14
      at Array.map (native)
      at Array.invoke (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\karma\node_modules\di\lib\injector.js:70:31)
      at [object Object].get (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\karma\node_modules\di\lib\injector.js:48:43)
       at instantiatePreprocessor (C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\karma\lib\preprocessor.js:56:37)
       at Array.forEach (native)
       at C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\karma\lib\preprocessor.js:77:31
      at C:\Users\dwaldo\Documents\endeavor-storefront\WebClient\node_modules\karma\lib\file_list.js:226:17
       at FSReqWrap.oncomplete (fs.js:95:15)

**Comment by kevinold** [comment]
@dgwaldo I ran into this issue earlier this week and an upgrade to karma 0.13.7 fixed the issue.  I'm still running karma-webpack 1.7.0.

**Comment by dgwaldo** [comment]
Sure enough that fixed it... :)
