### ISSUE TITLE
Karma fails to find karma-webpack 1.7.0

### ISSUE THREAD

**Issue by yyx990803** [webpack/karma-webpack#75]
Tested with karma 0.12.31 & 0.12.37. In both cases, karma-webpack 1.6.0 worked fine, but with 1.7.0 the following error is thrown:

```
WARN [preprocess]: Can not load "webpack"!
  TypeError: Object [object Object] has no method 'refreshFiles'
  at Plugin.notifyKarmaAboutChanges (/home/ubuntu/vue-router/node_modules/karma-webpack/index.js:108:15)
  at Plugin.<anonymous> (/home/ubuntu/vue-router/node_modules/karma-webpack/index.js:72:9)
  at Tapable.applyPlugins (/home/ubuntu/vue-router/node_modules/webpack/node_modules/tapable/lib/Tapable.js:26:37)
  at Watching._done (/home/ubuntu/vue-router/node_modules/webpack/lib/Compiler.js:78:17)
  at Watching.<anonymous> (/home/ubuntu/vue-router/node_modules/webpack/lib/Compiler.js:61:18)
  at Tapable.emitRecords (/home/ubuntu/vue-router/node_modules/webpack/lib/Compiler.js:281:37)
  at Watching.<anonymous> (/home/ubuntu/vue-router/node_modules/webpack/lib/Compiler.js:58:19)
  at /home/ubuntu/vue-router/node_modules/webpack/lib/Compiler.js:274:11
  at Tapable.applyPluginsAsync (/home/ubuntu/vue-router/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
  at Tapable.afterEmit (/home/ubuntu/vue-router/node_modules/webpack/lib/Compiler.js:271:8)
  at Tapable.<anonymous> (/home/ubuntu/vue-router/node_modules/webpack/lib/Compiler.js:266:14)
  at /home/ubuntu/vue-router/node_modules/webpack/node_modules/async/lib/async.js:52:16
  at Object.async.forEachOf.async.eachOf (/home/ubuntu/vue-router/node_modules/webpack/node_modules/async/lib/async.js:236:20)
  at Object.async.forEach.async.each (/home/ubuntu/vue-router/node_modules/webpack/node_modules/async/lib/async.js:215:22)
  at Tapable.emitFiles (/home/ubuntu/vue-router/node_modules/webpack/lib/Compiler.js:234:20)
  at MemoryFileSystem.(anonymous function) [as mkdirp] (/home/ubuntu/vue-router/node_modules/karma-webpack/node_modules/webpack-dev-middleware/node_modules/memory-fs/lib/MemoryFileSystem.js:197:10)
  at Tapable.<anonymous> (/home/ubuntu/vue-router/node_modules/webpack/lib/Compiler.js:228:25)
  at Tapable.applyPluginsAsync (/home/ubuntu/vue-router/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
  at Tapable.Compiler.emitAssets (/home/ubuntu/vue-router/node_modules/webpack/lib/Compiler.js:225:7)
  at Watching.<anonymous> (/home/ubuntu/vue-router/node_modules/webpack/lib/Compiler.js:54:18)
  at /home/ubuntu/vue-router/node_modules/webpack/lib/Compiler.js:402:12
  at Tapable.next (/home/ubuntu/vue-router/node_modules/webpack/node_modules/tapable/lib/Tapable.js:67:11)
  at Tapable.<anonymous> (/home/ubuntu/vue-router/node_modules/webpack/lib/CachePlugin.js:40:4)
  at Tapable.applyPluginsAsync (/home/ubuntu/vue-router/node_modules/webpack/node_modules/tapable/lib/Tapable.js:71:13)
  at Tapable.<anonymous> (/home/ubuntu/vue-router/node_modules/webpack/lib/Compiler.js:399:9)
  at Tapable.<anonymous> (/home/ubuntu/vue-router/node_modules/webpack/lib/Compilation.js:574:13)
  at Tapable.applyPluginsAsync (/home/ubuntu/vue-router/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
  at Tapable.<anonymous> (/home/ubuntu/vue-router/node_modules/webpack/lib/Compilation.js:569:10)
  at Tapable.applyPluginsAsync (/home/ubuntu/vue-router/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
  at Tapable.<anonymous> (/home/ubuntu/vue-router/node_modules/webpack/lib/Compilation.js:564:9)
  at Tapable.applyPluginsAsync (/home/ubuntu/vue-router/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
  at Tapable.<anonymous> (/home/ubuntu/vue-router/node_modules/webpack/lib/Compilation.js:560:8)
  at Tapable.applyPluginsAsync (/home/ubuntu/vue-router/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
  at Tapable.seal (/home/ubuntu/vue-router/node_modules/webpack/lib/Compilation.js:522:7)
  at Tapable.<anonymous> (/home/ubuntu/vue-router/node_modules/webpack/lib/Compiler.js:396:15)
  at /home/ubuntu/vue-router/node_modules/webpack/node_modules/tapable/lib/Tapable.js:103:11
  at Object.async.each (/home/ubuntu/vue-router/node_modules/karma-webpack/node_modules/async/lib/async.js:118:20)
  at Plugin.make (/home/ubuntu/vue-router/node_modules/karma-webpack/index.js:118:8)
  at Tapable.applyPluginsParallel (/home/ubuntu/vue-router/node_modules/webpack/node_modules/tapable/lib/Tapable.js:107:14)
  at Tapable.Compiler.compile (/home/ubuntu/vue-router/node_modules/webpack/lib/Compiler.js:393:7)
  at Watching.<anonymous> (/home/ubuntu/vue-router/node_modules/webpack/lib/Compiler.js:46:17)
  at Tapable.next (/home/ubuntu/vue-router/node_modules/webpack/node_modules/tapable/lib/Tapable.js:67:11)
  at Tapable.invalidAsyncPlugin (/home/ubuntu/vue-router/node_modules/karma-webpack/node_modules/webpack-dev-middleware/middleware.js:78:3)
  at Tapable.applyPluginsAsync (/home/ubuntu/vue-router/node_modules/webpack/node_modules/tapable/lib/Tapable.js:71:13)
  at Watching._go (/home/ubuntu/vue-router/node_modules/webpack/lib/Compiler.js:44:16)
  at Watching.<anonymous> (/home/ubuntu/vue-router/node_modules/webpack/lib/Compiler.js:36:8)
  at Tapable.readRecords (/home/ubuntu/vue-router/node_modules/webpack/lib/Compiler.js:301:10)
  at new Watching (/home/ubuntu/vue-router/node_modules/webpack/lib/Compiler.js:33:16)
  at Tapable.Compiler.watch (/home/ubuntu/vue-router/node_modules/webpack/lib/Compiler.js:160:17)
  at new module.exports (/home/ubuntu/vue-router/node_modules/karma-webpack/node_modules/webpack-dev-middleware/middleware.js:103:27)
  at new Plugin (/home/ubuntu/vue-router/node_modules/karma-webpack/index.js:88:37)
  at invoke (/home/ubuntu/vue-router/node_modules/karma/node_modules/di/lib/injector.js:75:15)
  at Array.instantiate [as 0] (/home/ubuntu/vue-router/node_modules/karma/node_modules/di/lib/injector.js:59:20)
  at get (/home/ubuntu/vue-router/node_modules/karma/node_modules/di/lib/injector.js:48:43)
  at /home/ubuntu/vue-router/node_modules/karma/node_modules/di/lib/injector.js:71:14
  at Array.map (native)
  at Array.invoke [as 0] (/home/ubuntu/vue-router/node_modules/karma/node_modules/di/lib/injector.js:70:31)
  at [object Object].get (/home/ubuntu/vue-router/node_modules/karma/node_modules/di/lib/injector.js:48:43)
  at instantiatePreprocessor (/home/ubuntu/vue-router/node_modules/karma/lib/preprocessor.js:56:37)
  at Array.forEach (native)
  at /home/ubuntu/vue-router/node_modules/karma/lib/preprocessor.js:77:31
  at /home/ubuntu/vue-router/node_modules/karma/lib/file_list.js:226:17
  at Object.oncomplete (fs.js:107:15)
```

**Comment by yyx990803** [comment]
nvm, it seems upgrading karma to 0.13 should fix the issue.
