### ISSUE TITLE
Multiple webpack configurations doesn't seem to work

### ISSUE THREAD

**Issue by aaronjensen** [webpack/karma-webpack#77]
For starters, I don't really know what multiple webpack configurations is for. I'm looking into it only because of #76.  

I basically just added my webpack configuration twice to `webpack:` in `karma.conf.js` and running some tests fails immediately:

```
$ ./node_modules/.bin/karma start --single-run

Child
    Time: 6ms
Child
    Time: 1ms
webpack: bundle is now VALID.
Error: callback(): The callback was already called.
    at Object.context.callback (/home/vagrant/.cid/project/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:143:11)
    at Object.module.exports (/home/vagrant/.cid/project/node_modules/karma-webpack/mocha-env-loader.js:30:7)
    at WEBPACK_CORE_LOADER_EXECUTION (/home/vagrant/.cid/project/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:155:71)
    at runSyncOrAsync (/home/vagrant/.cid/project/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:155:93)
    at nextLoader (/home/vagrant/.cid/project/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
    at /home/vagrant/.cid/project/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at context.callback (/home/vagrant/.cid/project/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
    at /home/vagrant/.cid/project/node_modules/babel-loader/index.js:65:14
    at /home/vagrant/.cid/project/node_modules/babel-loader/lib/fs-cache.js:135:24
    at /home/vagrant/.cid/project/node_modules/babel-loader/lib/fs-cache.js:40:14
    at Gunzip.onEnd (zlib.js:166:5)
    at Gunzip.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
Error: callback(): The callback was already called.
    at Object.context.callback (/home/vagrant/.cid/project/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:143:11)
    at Object.module.exports (/home/vagrant/.cid/project/node_modules/karma-webpack/mocha-env-loader.js:30:7)
    at WEBPACK_CORE_LOADER_EXECUTION (/home/vagrant/.cid/project/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:155:71)
    at runSyncOrAsync (/home/vagrant/.cid/project/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:155:93)
    at nextLoader (/home/vagrant/.cid/project/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
    at /home/vagrant/.cid/project/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at context.callback (/home/vagrant/.cid/project/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
    at /home/vagrant/.cid/project/node_modules/babel-loader/index.js:65:14
    at /home/vagrant/.cid/project/node_modules/babel-loader/lib/fs-cache.js:135:24
    at /home/vagrant/.cid/project/node_modules/babel-loader/lib/fs-cache.js:40:14
    at Gunzip.onEnd (zlib.js:166:5)
    at Gunzip.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
Error: callback(): The callback was already called.
    at Object.context.callback (/home/vagrant/.cid/project/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:143:11)
    at Object.module.exports (/home/vagrant/.cid/project/node_modules/karma-webpack/mocha-env-loader.js:30:7)
    at WEBPACK_CORE_LOADER_EXECUTION (/home/vagrant/.cid/project/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:155:71)
    at runSyncOrAsync (/home/vagrant/.cid/project/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:155:93)
    at nextLoader (/home/vagrant/.cid/project/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
    at /home/vagrant/.cid/project/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at context.callback (/home/vagrant/.cid/project/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
    at /home/vagrant/.cid/project/node_modules/babel-loader/index.js:65:14
    at /home/vagrant/.cid/project/node_modules/babel-loader/lib/fs-cache.js:135:24
    at /home/vagrant/.cid/project/node_modules/babel-loader/lib/fs-cache.js:40:14
    at Gunzip.onEnd (zlib.js:166:5)
    at Gunzip.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
Error: callback(): The callback was already called.
    at Object.context.callback (/home/vagrant/.cid/project/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:143:11)
    at Object.module.exports (/home/vagrant/.cid/project/node_modules/karma-webpack/mocha-env-loader.js:30:7)
    at WEBPACK_CORE_LOADER_EXECUTION (/home/vagrant/.cid/project/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:155:71)
    at runSyncOrAsync (/home/vagrant/.cid/project/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:155:93)
    at nextLoader (/home/vagrant/.cid/project/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
    at /home/vagrant/.cid/project/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at context.callback (/home/vagrant/.cid/project/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
    at /home/vagrant/.cid/project/node_modules/babel-loader/index.js:65:14
    at /home/vagrant/.cid/project/node_modules/babel-loader/lib/fs-cache.js:135:24
    at /home/vagrant/.cid/project/node_modules/babel-loader/lib/fs-cache.js:40:14
    at Gunzip.onEnd (zlib.js:166:5)
    at Gunzip.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
Error: callback(): The callback was already called.
    at Object.context.callback (/home/vagrant/.cid/project/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:143:11)
    at Object.module.exports (/home/vagrant/.cid/project/node_modules/karma-webpack/mocha-env-loader.js:30:7)
    at WEBPACK_CORE_LOADER_EXECUTION (/home/vagrant/.cid/project/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:155:71)
    at runSyncOrAsync (/home/vagrant/.cid/project/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:155:93)
    at nextLoader (/home/vagrant/.cid/project/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
    at /home/vagrant/.cid/project/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at context.callback (/home/vagrant/.cid/project/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
    at /home/vagrant/.cid/project/node_modules/babel-loader/index.js:65:14
    at /home/vagrant/.cid/project/node_modules/babel-loader/lib/fs-cache.js:135:24
    at /home/vagrant/.cid/project/node_modules/babel-loader/lib/fs-cache.js:40:14
    at Gunzip.onEnd (zlib.js:166:5)
    at Gunzip.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
Error: callback(): The callback was already called.
    at Object.context.callback (/home/vagrant/.cid/project/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:143:11)
    at Object.module.exports (/home/vagrant/.cid/project/node_modules/karma-webpack/mocha-env-loader.js:30:7)
    at WEBPACK_CORE_LOADER_EXECUTION (/home/vagrant/.cid/project/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:155:71)
    at runSyncOrAsync (/home/vagrant/.cid/project/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:155:93)
    at nextLoader (/home/vagrant/.cid/project/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
    at /home/vagrant/.cid/project/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at context.callback (/home/vagrant/.cid/project/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
    at /home/vagrant/.cid/project/node_modules/babel-loader/index.js:65:14
    at /home/vagrant/.cid/project/node_modules/babel-loader/lib/fs-cache.js:135:24
    at /home/vagrant/.cid/project/node_modules/babel-loader/lib/fs-cache.js:40:14
    at Gunzip.onEnd (zlib.js:166:5)
    at Gunzip.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
Child
    Time: 6ms
Child
    Time: 1048ms
webpack: bundle is now VALID.
21 08 2015 04:54:13.383:ERROR [karma]: [Error: Path doesn't exist '/_karma_webpack_/0/specs/ajax.spec.js']
Error: Path doesn't exist '/_karma_webpack_/0/specs/ajax.spec.js'
    at MemoryFileSystem.readFileSync (/home/vagrant/.cid/project/node_modules/karma-webpack/node_modules/webpack-dev-middleware/node_modules/memory-fs/lib/MemoryFileSystem.js:79:10)
    at MemoryFileSystem.readFile (/home/vagrant/.cid/project/node_modules/karma-webpack/node_modules/webpack-dev-middleware/node_modules/memory-fs/lib/MemoryFileSystem.js:207:21)
    at /home/vagrant/.cid/project/node_modules/karma-webpack/index.js:145:27
    at /home/vagrant/.cid/project/node_modules/karma-webpack/node_modules/async/lib/async.js:246:17
    at /home/vagrant/.cid/project/node_modules/karma-webpack/node_modules/async/lib/async.js:122:13
    at _each (/home/vagrant/.cid/project/node_modules/karma-webpack/node_modules/async/lib/async.js:46:13)
    at async.each (/home/vagrant/.cid/project/node_modules/karma-webpack/node_modules/async/lib/async.js:121:9)
    at _asyncMap (/home/vagrant/.cid/project/node_modules/karma-webpack/node_modules/async/lib/async.js:245:13)
    at Object.map (/home/vagrant/.cid/project/node_modules/karma-webpack/node_modules/async/lib/async.js:216:23)
    at Object.async.times (/home/vagrant/.cid/project/node_modules/karma-webpack/node_modules/async/lib/async.js:1040:22)
    at doRead (/home/vagrant/.cid/project/node_modules/karma-webpack/index.js:144:10)
    at Plugin.readFile (/home/vagrant/.cid/project/node_modules/karma-webpack/index.js:177:3)
    at process._tickCallback (node.js:415:13)
21 08 2015 04:54:13.389:ERROR [karma]: [Error: Path doesn't exist '/_karma_webpack_/0/specs/merge.spec.js']
Error: Path doesn't exist '/_karma_webpack_/0/specs/merge.spec.js'
    at MemoryFileSystem.readFileSync (/home/vagrant/.cid/project/node_modules/karma-webpack/node_modules/webpack-dev-middleware/node_modules/memory-fs/lib/MemoryFileSystem.js:79:10)
    at MemoryFileSystem.readFile (/home/vagrant/.cid/project/node_modules/karma-webpack/node_modules/webpack-dev-middleware/node_modules/memory-fs/lib/MemoryFileSystem.js:207:21)
    at /home/vagrant/.cid/project/node_modules/karma-webpack/index.js:145:27
    at /home/vagrant/.cid/project/node_modules/karma-webpack/node_modules/async/lib/async.js:246:17
    at /home/vagrant/.cid/project/node_modules/karma-webpack/node_modules/async/lib/async.js:122:13
    at _each (/home/vagrant/.cid/project/node_modules/karma-webpack/node_modules/async/lib/async.js:46:13)
    at async.each (/home/vagrant/.cid/project/node_modules/karma-webpack/node_modules/async/lib/async.js:121:9)
    at _asyncMap (/home/vagrant/.cid/project/node_modules/karma-webpack/node_modules/async/lib/async.js:245:13)
    at Object.map (/home/vagrant/.cid/project/node_modules/karma-webpack/node_modules/async/lib/async.js:216:23)
    at Object.async.times (/home/vagrant/.cid/project/node_modules/karma-webpack/node_modules/async/lib/async.js:1040:22)
    at doRead (/home/vagrant/.cid/project/node_modules/karma-webpack/index.js:144:10)
    at Plugin.readFile (/home/vagrant/.cid/project/node_modules/karma-webpack/index.js:177:3)
    at process._tickCallback (node.js:415:13)
Child
    Time: 1195ms
Child
    Time: 1048ms
webpack: bundle is now VALID.
Unhandled rejection Error: Not running
    at Server.close (net.js:1236:11)
    at /home/vagrant/.cid/project/node_modules/karma/lib/server.js:334:17
    at tryCatcher (/home/vagrant/.cid/project/node_modules/karma/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/vagrant/.cid/project/node_modules/karma/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/home/vagrant/.cid/project/node_modules/karma/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/home/vagrant/.cid/project/node_modules/karma/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/home/vagrant/.cid/project/node_modules/karma/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/vagrant/.cid/project/node_modules/karma/node_modules/bluebird/js/main/async.js:133:10)
    at Async.drainQueues (/home/vagrant/.cid/project/node_modules/karma/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickCallback (node.js:415:13)
Unhandled rejection Error: Not running
    at Server.close (net.js:1236:11)
    at /home/vagrant/.cid/project/node_modules/karma/lib/server.js:334:17
    at tryCatcher (/home/vagrant/.cid/project/node_modules/karma/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/vagrant/.cid/project/node_modules/karma/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/home/vagrant/.cid/project/node_modules/karma/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/home/vagrant/.cid/project/node_modules/karma/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/home/vagrant/.cid/project/node_modules/karma/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/vagrant/.cid/project/node_modules/karma/node_modules/bluebird/js/main/async.js:133:10)
    at Async.drainQueues (/home/vagrant/.cid/project/node_modules/karma/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickCallback (node.js:415:13)
```

I can put together my webpack config and karma config if it'd be helpful.

**Comment by magnli10** [comment]
I recently bumped into this issue as well [Path is a file error loading tests with Karma and Webpack](http://stackoverflow.com/questions/32201797/path-is-a-file-error-loading-tests-with-karma-and-webpack).

**Comment by graingert** [comment]
see @aaronjensen https://github.com/webpack/karma-webpack/blob/master/example/karma-complex.conf.js for an example

**Comment by d3viant0ne** [comment]
Closing this as there are resolutions in both the [StackOverflow question](http://stackoverflow.com/questions/32201797/path-is-a-file-error-loading-tests-with-karma-and-webpack) and it's comment ( specific to the error above ) and the complex config in the example directory.
