### ISSUE TITLE
Broken with Node 4.1.2 and npm 2.14.2 on Ubuntu

### ISSUE THREAD

**Issue by austinpray** [webpack/karma-webpack#86]
Here is a sample build: https://travis-ci.org/UTD-CRSS/app.exploreapollo.org/builds/84156931

```
07 10 2015 18:46:18.065:ERROR [karma]: [Error: Path doesn't exist '/_karma_webpack_/tests.webpack.js']
Error: Path doesn't exist '/_karma_webpack_/tests.webpack.js'
    at MemoryFileSystem.readFileSync (/home/travis/build/UTD-CRSS/app.exploreapollo.org/node_modules/webpack-dev-middleware/node_modules/memory-fs/lib/MemoryFileSystem.js:79:10)
    at MemoryFileSystem.readFile (/home/travis/build/UTD-CRSS/app.exploreapollo.org/node_modules/webpack-dev-middleware/node_modules/memory-fs/lib/MemoryFileSystem.js:207:21)
    at doRead (/home/travis/build/UTD-CRSS/app.exploreapollo.org/node_modules/karma-webpack/index.js:156:26)
    at Plugin.readFile (/home/travis/build/UTD-CRSS/app.exploreapollo.org/node_modules/karma-webpack/index.js:160:3)
    at doNTCallback0 (node.js:408:9)
    at process._tickCallback (node.js:337:13)
```

The build succeeds using npm@latest. It only fails when npm is 2.14.2 (what ships with node 4.1.2).

**Comment by eddiemoore** [comment]
+1 I'm facing the same issue. Works on my local machine but not working on Codeship as they are using Ubuntu

**Comment by vyorkin** [comment]
thank you so much guys for sharing this, works on `npm@latest`
